### ISSUE TITLE
Cannot use template

### ISSUE THREAD

**Issue by aburd** [xilk-org/xilk-xp-web-app-template#1]
### Prerequisites

- [X] I agree to follow the [rules for contributors](../blob/main/doc/CONTRIBUTING.md#rules).
- [X] I have read [How to Report a Bug](../blob/main/doc/CONTRIBUTING.md#how-to-report-a-bug).
- [X] I have searched [existing issues](./), and found none matching this bug.

### Expected Behavior

When I follow the instructions on [getting started](https://github.com/xilk-org/xilk-xp-web-app-template#getting-started), I would expect the template to be generated.

### Actual Behavior

cd: The directory “../my-project-dir” does not exist

### Steps to Reproduce

1. I have leiningen installed
2. I cloned the repo
3. I tried the "Create a new project and change directory." step

### Template Version

"20220608-4"

### Additional Info

I'm a beginner with leiningen and templates in general, but I've found other templates to be more straightforward (i.e. https://github.com/cryogen-project/cryogen).

So I'm not sure if this is a "bug" or if I'm just missing context, but I'm a bit lost as to where to go from here.

**Comment by aburd** [comment]
I tried to follow this instructions on [leiningen templates](https://github.com/technomancy/leiningen/blob/master/doc/TEMPLATES.md)

```
⋊> ~/C/a/xilk-xp-web-app-template on main ◦ pwd                                                                                                                                                                                         17:04:59
/home/aburd/Code/aburd/xilk-xp-web-app-template
⋊> ~/C/a/xilk-xp-web-app-template on main ◦ lein new org.xilk/xp-web-app myproject                                                                                                                                                      17:07:11
Failed to resolve version for org.xilk/xp-web-app:lein-template:jar:RELEASE: Could not find metadata org.xilk/xp-web-app:lein-template/maven-metadata.xml in local (/home/aburd/.m2/repository)
Failed to resolve version for org.xilk/xp-web-app:lein-template:jar:RELEASE: Could not find metadata org.xilk/xp-web-app:lein-template/maven-metadata.xml in local (/home/aburd/.m2/repository)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
Could not find template org.xilk/xp-web-app on the classpath.
```

**Comment by aburd** [comment]
Ok, it worked as expected when I ran `lein new xp-web-app myproject`.

I guess I would expect step 3 of the instructions to read like this:

```
cd xilk-xp-web-app-template
lein new xp-web-app my-project-name --to-dir ../my-project-dir
cd ../my-project-dir
```

Unless I'm missing something?

**Comment by stevejmp** [comment]
OMG, I apologize for the delay. I wrongly assumed notifications on issues were on by default. So sorry!

I just tested on my machine, and both ways work:
```sh
lein new org.xilk/xp-web-app ...
```
```sh
lein new xp-web-app ...
```

I'm going to update the README with the latter in case others have that issue, too. Thanks so much for the feedback!

**Comment by stevejmp** [comment]
> I'm a beginner with leiningen and templates in general, but I've found other templates to be more straightforward (i.e. https://github.com/cryogen-project/cryogen).

I definitely agree! Production templates are usually deployed to [Clojars](https://clojars.org/) so that they can be accessed via `lein` without having to clone the template repo.

This is an R&D template for iterating on patterns and API's. That means lots of breaking changes. I think Clojure devs tend to expect that tools they pull from Clojars are, at the very least, more mature than that, so I decided to not deploy to Clojars at this point. That does make using this template a bit more of a hassle, and I'm grateful to you for making the extra effort to try things out and give feedback. Thanks again!

Once I feel that the API's are solid, I am planning to break the libraries out to their own repos, deploy them to Clojars, and do something template-wise similar to what Cryogen does, where devs can use their choice of tools to build. This will be the point where we shift from R&D to production.

Hope this helps!

**Comment by aburd** [comment]
Ahhh, I figured it was something to do with my machine or something.

> I don't know why the former isn't working for you, but I'm going to update the README with the latter in case others have that issue, too.

Sounds good! Thanks for your help!
